remote_theme: minicomp/ed

# Setup
title: Emperor of the Moon
tagline: 'Bryn Mawr College, ARTT B243'
description: 'Research for the Spring 2020 production of Emperor of the Moon by Aphra Behn.'
url: 'https://digbmc.github.io'
baseurl:  /emperor-moon

# About/contact

# author:
#  name:

# Permalinks

# Color scheme. Options: red, orange, magenta, cyan, blue, brown
color-scheme: cyan

permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  posts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Exclusions from the final site
exclude:
  - optional
  - vendor

# Prose

prose:
  rooturl: '_posts'
  siteurl: 'http://digbmc.github.io/emperor-moon/'
#  relativeLinks: 'http://digbmc.github.io/emperor-moon/links.jsonp'
  media: 'media'
  ignore:
    - _config.yml
    - LICENSE
  metadata:
    _posts:
      - name: "user"
        field:
          element: "hidden"
          value: CURRENT_USER
      - name: "author"
        field:
          element: "text"
          label: "Author of this post"
          value: ""
      - name: "category"
        field:
          element: "hidden"
          value: "blog"
      - name: "layout"
        field:
          element: "text"
          label: "Layout"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "splash"
        field:
          element: "text"
          label: "Splash image"
          value: ""
      - name: "published"
        field:
          element: "button"
          label: "Publish this post?"
          on: true
          off: false
